### ISSUE TITLE
How to set up the project 

### ISSUE THREAD

**Issue by vendkura** [project-SIMPLE/web-platform#5]
# STEP1 : Cloning the repo
1. Clone the repository by typing the following command `git clone https://github.com/project-SIMPLE/web-platform.git`
2. Switch main branch to : `version_2_init ` branch.

# STEP2 : Install the dependencies
1. First install pnpm by typing this command : `npm install -g pnpm`
2. Install the packages : `pnpm install`

# STEP3 : Launch Gama

# STEP4 : Start the project
- Type this command to start the project : `pnpm start` : You should have some logs on your terminal

# STEP5 : Access to the middleware

- Go on your browser and insert this to the search bar : `http://localhost:3333`

**Comment by RoiArthurB** [comment]
Closing with commit d38f3ce
